version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && rails server -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ubuntu # Change this to your PostgreSQL user
      POSTGRES_PASSWORD: ahmed  # Change this to your PostgreSQL password
      POSTGRES_DB: myapp_development  # Change this to your database name
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

