apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-postgres
  namespace: myapp
spec:
  serviceName: "myapp-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: myapp-postgres
  template:
    metadata:
      labels:
        app: myapp-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: ubuntu
        - name: POSTGRES_PASSWORD
          value: ahmed  # Change this to your PostgreSQL password
        - name: POSTGRES_DB
          value: "myapp_development"  # Change this to your database name
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

