apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: ahmed8d99/myapp_web:latest  # Replace with your Docker Hub image
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://ubuntu:ahmed@postgres/myapp_development  # Update as needed
          command: ["bash", "-c", "rm -f tmp/pids/server.pid && rails db:migrate && rails server -b '0.0.0.0'"]
---
apiVersion: v1
kind: Service
metadata:
  name: rails-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: rails-app

